### ISSUE TITLE
Ability to stop/pause a pipeline instance using API

### ISSUE THREAD

**Issue by jemshad** [tremor-rs/tremor-runtime#1006]
**Describe the problem you are trying to solve**

In the case of tremor having multiple onramps and multiple offramps each connected through the pipeline in a 1:1 fashion, when a particular offramp is under maintenance, we would like to have tremor stop consuming events from the corresponding onramp. This would be a clean solution rather than having tremor keep retrying on the unavailable offramp resulting to either bad metrics and/or overhead in processing the events that resulted in error.

**Describe the solution you'd like**

In the particular case that we are talking about, the different oramps are connected to respective offramps using the `binding` and `mapping` configurations. Effectively, each instance is consuming from a different onramp and posting messages to the corresponding offramp. If we can dynamically pause the pipeline and stop consumption from the `onramp` for a particular instance, that would be awesome.

**Notes**

**Comment by mfelsche** [comment]
This is being done as part of the work on connectors.

**Comment by mfelsche** [comment]
This is possible since 0.12
