### ISSUE TITLE
Wildly unsound use of `transmute` across whole project

### ISSUE THREAD

**Issue by Voultapher** [tremor-rs/tremor-runtime#1015]
**Problem**

Borderline every time `transmute` is used in this project it's unsound and wrong! Especially in the context of self-referential structs.

I've been going through rental dependents and replacing them with [self_cell](https://github.com/Voultapher/self_cell) eg. https://github.com/matklad/fall/pull/6#issuecomment-841620597 as it's no longer maintained and users are encouraged to switch to another solution.

I started by trying to replace the use for `LineValue`, immediately I noticed the alarming use of `transmute`.

> tremor-script/src/lib.rs:204
```rust
/// Borrow the parts (event and metadata) from a rental.
/// This borrows the data as immutable and then transmutes it
/// to be mutable.
#[allow(mutable_transmutes, clippy::transmute_ptr_to_ptr)]
#[must_use]
pub fn parts<'value, 'borrow>(
    &'borrow self,
) -> (&'borrow mut Value<'value>, &'borrow mut Value<'value>)
where
    'borrow: 'value,
{
    unsafe {
        let data = self.suffix();
        let unwind_event: &'borrow mut Value<'value> = std::mem::transmute(data.value());
        let event_meta: &'borrow mut Value<'value> = std::mem::transmute(data.meta());
        (unwind_event, event_meta)
    }
}
```

Here as you say yourself, you take an immutable self and transmute it to be mutable. Also note this function isn't even marked as *unsafe*. It's called 27 times across the whole project in all kinds of places.

This is *not* the only time you do this. A further example from the same file:

> tremor-script/src/lib.rs:204
```rust
/// Event value forced to borrowd mutable (uses `mem::transmute`)
///
/// # Safety
/// This isn't save, use with care and reason about mutability!
#[allow(mutable_transmutes, clippy::transmute_ptr_to_ptr, clippy::mut_from_ref)]
#[must_use]
pub unsafe fn force_value_mut(&self) -> &mut Value<'event> {
    std::mem::transmute(&self.v)
}
```

Here you mark this function unsafe and remark `This isn't save, use with care and reason about mutability!`.

Let's quickly take a look at what the language specification has to say about this:

https://doc.rust-lang.org/nomicon/transmutes.html

> Transmuting an & to &mut is UB.
>
> - Transmuting an & to &mut is *always* UB.
> - No you can't do it.
> - No you're not special.

So no matter how careful you are when calling these functions, it will always instantly be wrong!

When I think of an event processing system, I expect it to be robust and reliable. You say 'Tremor runs 24x7 365 days per year and is implemented in the Rust programming language.' at the very beginning of you documentation. So I guess you care about this too.

But you know maybe I could fix this and replace this with safe abstractions along the way of migrating to self_cell, I though to myself. So I started dragging the new safe abstraction through the code. Soon I was faced with `consume` which presented a rather challenging problem. But I was motivated to find a safe solution, so I did some thinking and came up with an approach, rough sketch ![line_value_consume_idea](https://user-images.githubusercontent.com/6864584/118510148-f9ab5300-b730-11eb-8b52-f92f3494c65f.jpg)

```rust
// batch.rs

ValueMergeList instead of LineValue in Batch struct as data field.
{
owner: Vec<LineValue>
dependent: Vec<&'a Value<'a>>
}

// on_event

let mut line_values = self.data.into_owner();

event.data.with_dependent_mut(|_, parsed| {
    parsed = literal!({
        "data": {
            "value": parsed.value(),
            "meta": parsed.meta(),
            "ingest_ns": ingest_ns,
            "kind": Value::null(),
            "is_batch": is_batch
        }
    });
});
lines_values.push(event.data);

self.data = ValueMergeList::new(lines_values, |line_values| {
    let mut value_list_ref_list = line_values[0].as_array_mut();

    value_list_ref_list.push(e);

    value_list_ref_list
});

this.with_dependent_mut(|_, value_list_ref_list| {
    value_list_ref_list.push(other.borrow_dependent());
});
```

Pushing this back I continued by deleting the `parts` function and replacing it's use with either `borrow_dependent` or `with_dependent_mut` depending on the use case. In `history.rs on_event` I was faced with ever more complex lifetime issues where to safely mutate the dependent meta and I had to call `with_dependent_mut` but doing so locked away `event.id` which would have to be cloned before hand. Distraught by the complexity creep of this library replacement and the constant willful and frivolous *wrong* abuse of Rust, I searched for `transmute` in the project and was faced with **40** results across 14 files :O ! At this point I'd like to quote the nomicon's section about `transmute` again:

> Even though this book is all about doing things that are unsafe, I really can't emphasize that you should deeply think about finding Another Way than the operations covered in this section. This is really, truly, the most horribly unsafe thing you can do in Rust. The guardrails here are dental floss.

Especially when dealing with lifetimes. As the author of self_cell I can sing you a song about how easy it is to get lifetimes wrong with `transmute`, I have some 10 odd versions janked because they were unsound. And that's a well defined small problem and interface. Taking a look at the first result I got for `transmute` outside of `tremor-script/src/lib.rs` was at `tremor-cli/src/run.rs:348`:

```rust
ingress.process(
    &mut pipeline,
    id,
    &mut egress,
    &move |runnable, id, egress, at, event| {
        let value = LineValue::new(vec![], |_| unsafe {
            std::mem::transmute(ValueAndMeta::from(event.clone()))
        });

        let mut continuation = vec![];

        if let Err(e) = runnable.enqueue(
            "in",
            Event {
                id: EventId::new(0, 0, *id),
                data: value.clone(),
                ingest_ns: at,
                ..Event::default()
            },
            &mut continuation,
        ) {
            match e.0 {
                tremor_pipeline::errors::ErrorKind::Script(script_kind) => {
                    let script_error: tremor_script::errors::Error = script_kind.into();
                    if let (Some(r), _) = script_error.context() {
                        let mut inner = TermHighlighter::stderr();
                        let mut input = raw.clone();
                        input.push('\n'); // for nicer highlighting
                        let tokens: Vec<_> =
                            Tokenizer::new(&input).tokenize_until_err().collect();

                        if let Err(highlight_error) = inner.highlight_error(
                            Some(&src),
                            &tokens,
                            "",
                            true,
                            Some(r),
                            Some(HighlighterError::from(&script_error)),
                        ) {
                            eprintln!("Error during error highlighting: {}", highlight_error);
                            return Err(highlight_error.into());
                        }
                        inner.finalize()?;
                        return Ok(());
                    }
                }
                _ => {
                    return Err(e.into());
                }
            }
        }
        *id += 1;

        for (port, rvalue) in continuation.drain(..) {
            egress.process(
                &simd_json::to_string_pretty(&value.suffix().value())?,
                &event,
                Return::Emit {
                    value: rvalue.data.suffix().value().clone_static(),
                    port: Some(port.to_string()),
                },
            )?;
        }

        Ok(())
    },
)?;
```

You construct a new `LineValue` by saying the owner is an empty vector and lying about the lifetime of where the dependent `LineValue` comes from, `clone` that resulting object, pass it into some some queue, where it will be alive for who knows how long, use it 40 lines later to serialize it to JSON all the while transmuting another `Value` into a `'static` lifetime with `clone_static` which also underlies the `ValueAndMeta::clone`, literally taking a bound lifetime object and claiming no it's fine it lives forever don't need to do any of that pesky borrow checking. Are you really sure you can guarantee that not a single aliasing rule was broken in any of these cloned values, as they interact with the `parts` function that gives you an unlimited amount of mutable borrows inside the various process functions?

Unsurprisingly running any test that touch `Value` with miri blows up immideately at one of the transmutes, eg:

```
$ cargo +nightly miri test executable_graph

test executable_graph::test::eg_metrics ... error: Undefined Behavior: trying to reborrow for Unique at alloc189445+0x30, but parent tag <468571> does not have an appropriate item in the borrow stack
--> tremor-runtime/tremor-script/src/lib.rs:217:60
|
217 |             let unwind_event: &'borrow mut Value<'value> = std::mem::transmute(data.value());
|                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ trying to reborrow for Unique at alloc189445+0x30, but parent tag <468571> does not have an appropriate item in the borrow stack
|
= help: this indicates a potential bug in the program: it performed an invalid operation, but the rules it violated are still experimental
= help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information

= note: inside `tremor_script::<impl tremor_script::LineValue>::parts` at tremor-runtime/tremor-script/src/lib.rs:217:60
note: inside `executable_graph::test::test_metrics` at tremor-pipeline/src/executable_graph.rs:746:25
--> tremor-pipeline/src/executable_graph.rs:746:25
|
746 |         let (data, _) = this.data.parts();
|                         ^^^^^^^^^^^^^^^^^
note: inside `executable_graph::test::eg_metrics` at tremor-pipeline/src/executable_graph.rs:858:9
--> tremor-pipeline/src/executable_graph.rs:858:9
|
858 |         test_metrics(metrics, 1);
|         ^^^^^^^^^^^^^^^^^^^^^^^^
note: inside closure at tremor-pipeline/src/executable_graph.rs:789:5
--> tremor-pipeline/src/executable_graph.rs:789:5
|
789 | /     fn eg_metrics() {
790 | |         let mut in_n = pass(1, "in");
791 | |         in_n.kind = NodeKind::Input;
792 | |         let mut out_n = pass(2, "out");
...   |
877 | |         test_metrics(metrics, 3);
878 | |     }
| |_____^
= note: inside `<[closure@tremor-pipeline/src/executable_graph.rs:789:5: 878:6] as std::ops::FnOnce<()>>::call_once - shim` at.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
= note: inside `<fn() as std::ops::FnOnce<()>>::call_once - shim(fn())` at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
= note: inside `test::test::__rust_begin_short_backtrace::<fn()>` at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:567:5
= note: inside closure at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:558:30
= note: inside `<[closure@test::test::run_test::{closure#2}] as std::ops::FnOnce<()>>::call_once - shim(vtable)` at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
= note: inside `<std::boxed::Box<dyn std::ops::FnOnce() + std::marker::Send> as std::ops::FnOnce<()>>::call_once` at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1546:9
= note: inside `<std::panic::AssertUnwindSafe<std::boxed::Box<dyn std::ops::FnOnce() + std::marker::Send>> as std::ops::FnOnce<()>>::call_once` at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
= note: inside `std::panicking::r#try::do_call::<std::panic::AssertUnwindSafe<std::boxed::Box<dyn std::ops::FnOnce() + std::marker::Send>>, ()>` at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
= note: inside `std::panicking::r#try::<(), std::panic::AssertUnwindSafe<std::boxed::Box<dyn std::ops::FnOnce() + std::marker::Send>>>` at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
= note: inside `std::panic::catch_unwind::<std::panic::AssertUnwindSafe<std::boxed::Box<dyn std::ops::FnOnce() + std::marker::Send>>, ()>` at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
= note: inside `test::test::run_test_in_process` at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:589:18
= note: inside closure at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:486:39
= note: inside `test::test::run_test::run_test_inner` at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:522:13
= note: inside `test::test::run_test` at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:555:28
= note: inside `test::test::run_tests::<[closure@test::test::run_tests_console::{closure#2}]>` at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:301:17
= note: inside `test::test::run_tests_console` at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/console.rs:289:5
= note: inside `test::test::test_main` at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:121:15
= note: inside `test::test::test_main_static` at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:140:5
= note: inside `main`
= note: inside `<fn() as std::ops::FnOnce<()>>::call_once - shim(fn())` at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
= note: inside `std::sys_common::backtrace::__rust_begin_short_backtrace::<fn(), ()>` at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
= note: inside closure at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66:18
= note: inside `std::ops::function::impls::<impl std::ops::FnOnce<()> for &dyn std::ops::Fn() -> i32 + std::marker::Sync + std::panic::RefUnwindSafe>::call_once` at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:259:13
= note: inside `std::panicking::r#try::do_call::<&dyn std::ops::Fn() -> i32 + std::marker::Sync + std::panic::RefUnwindSafe, i32>` at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
= note: inside `std::panicking::r#try::<i32, &dyn std::ops::Fn() -> i32 + std::marker::Sync + std::panic::RefUnwindSafe>` at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
= note: inside `std::panic::catch_unwind::<&dyn std::ops::Fn() -> i32 + std::marker::Sync + std::panic::RefUnwindSafe, i32>` at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
= note: inside `std::rt::lang_start_internal` at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:51:25
= note: inside `std::rt::lang_start::<()>` at .rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65:5
= note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

Even if somehow the current code is somewhat functional, I guarantee you there are edge cases you missed, future compiler optimization and more that will break the current code and put you into the very unpleasant land of Undefined Behavior. And even worse the concepts at play here are so incredibly complex, every future code change has a *very* real chance of messing it up, if not here in one of the other who knows how many places that interact with the abstractions you built on top of 40 wrong `transmute`s.

I've published my changes so far here https://github.com/Voultapher/tremor-runtime/commit/738f08e5b716826c5c959b4aa6bd4f8c34fde66e.

**Steps**

Search for `transmute` in the code.

**Possible Solution(s)**

Deep refactor of the project, forbid any `transmute` usage! For extreme exceptions factor it out into peer reviewed and miri tested crates.

**Comment by Licenser** [comment]
Hi @Voultapher,

Thank you for this detailed and well-thought-out issue and the considerable effort to try and replace `rental` with `self_cell`.

None of us are fans of unsafe code, or `mem::transmute`, and the borrow checker and other rust features are beneficial in building stable production-grade systems.

As the author of `self_cell`, this is clearly an area where you have invested huge efforts already and gained experience in that process. Tremor favors stable pragmatic production code over perfect code - if `self_cell` can move us away from some of our legacy decisions such as raw transmute or rental that’d be great; We would like to explore both the `self_cell` adoption and the removal of unsafe code where possible with you and with the broader tremor community. We are more than happy to eliminate the transmutes or other unsafe while maintaining our current performance profile.

Your commit message and phrasing in this issue gave us the impression that you are frustrated.  And, while frustration can get to the best of us, please take a look at our [Code of Conduct](https://github.com/tremor-rs/tremor-runtime/blob/main/CODE_OF_CONDUCT.md) to understand how the Tremor community works. We're always willing to improve and work with the community, but we ask that this be done with kindness, consideration for others, and an openness to new ideas.

**Comment by Voultapher** [comment]
You are right, let's focus on the technical side and keep this conversation friendly and productive. I will try my best to be less emotional in my communication. It's great to see you are taking this issue serious and are already taking first steps in addressing it. Given `transmute` usage is so wide spread in this project, changes will have to be incremental. I fully agree with starting small and https://github.com/tremor-rs/tremor-runtime/pull/1019 is a good first step. My coarse interaction with the places violating the & to &mut rules, showed the calling sites often to be easily amenable. Often a non ref value was the source and could easily be changed to be mut, eg:

history.rs before:

```rust
    [...]
    _state: &mut Value<'static>,
    event: Event,
) -> Result<EventAndInsights> {
    [...]
    event.function_taking_ref();
```

history.rs after:

```rust
    [...]
    _state: &mut Value<'static>,
    mut event: Event,
) -> Result<EventAndInsights> {
    [...]
    event.function_taking_mut_ref();
```

I suspect that replacing rental will be trickier and more involved, but surely there is a way with enough will and effort to make Tremor safer and more robust. I'll be happy to help you as I can. All this said, purely from a professional software-engineering point of view, I would certainly not call this use of `transmute` 'stable pragmatic production code', but rather distressingly irresponsible towards your users. So I'm happy to see you value the importance of this topic. And on the plus side should the idea for event merging pan out, one less pointer indirection for all events could net a noticeable performance win.

I took a look at https://github.com/tremor-rs/tremor-runtime/pull/1019 but I don't feel familiar enough with the code base to review it's correctness. I've joined the discord server so I'm open to chat about the specifics and implications of switching to self_cell, as well as general advice surrounding lifetimes and `transmute`.

**Comment by Licenser** [comment]
Awesome :)

follow-up, with #1019 being merged a lot of the transmutes, especially some of the problematic ones, are gone.

Those ones were all somewhat low-hanging fruit as they snuck in either from the borrow checker having false positives that are now resolved or some learning in how to re-structure code. Some of the big ones are that `parts` is gone (in the form it existed) and now is a safe function just referencing the two parts for convenience :D along with a number of times where `rent_mut` could replace a transmute.

There are however quite a number of places where transmute was challenging to remove every one of the instances got an own ticket, with the code tracking the relation, and are collected in a [project](https://github.com/tremor-rs/tremor-runtime/projects/6).

That way they can be tackled individually and the scope remains manageable and bounded. It also adds some context to the reason behind their existence, which is something some of them lacked beforehand.

**Comment by Voultapher** [comment]
The project is a great idea to keep track of 'The great un-transmutification of 2021' :laughing: . I would suggest adding a long-term ticket with the goal of running some of the tests with miri in the CI, this should help validate the results of this project and provide additional robustness going forward.

**Comment by Licenser** [comment]
With the split out of each single transmute into an own issue and creating a project to track them we're closing this collection issue as it's going to be easier to work with and track the separated ones.
