### ISSUE TITLE
Free kafka source from transmutes

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#1023]
**Describe the problem you are trying to solve**

The Kafka source depends on some transmutes that we should eliminate.

**Describe the solution you'd like**

a transmute-free Kafka source, there has to be a way!

**Notes**

Followup to #1015

**Comment by mfelsche** [comment]
One simple way would be to switch it back to sync polling mode, but this would run us into possible poll timeouts when we pause or when the CB is triggered.

**Comment by Licenser** [comment]
Ja the polling was a bad :tm: thing, I'm not sure what the best way here is but it'd be good to get rid of ti, perhaps the API of librdkfakfa could be extended to cover the requirement? It seems like a good thing to have an  API that allows both manual acknowledgments and streaming

**Comment by Licenser** [comment]
It'll be nice to look at this along with the connector update, I'll add it to the project :) perhaps we can look into possibilities when turning the source into a connector

**Comment by Licenser** [comment]
A bit issue here is that this mixes rentals and async, so `rent_mut` that gets around a lot of the transmuting borrows doesn't work well (at all) with async.
