### ISSUE TITLE
generic consume to remove the need for a rental

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#1031]
**Describe the problem you are trying to solve**

For combining two borrowed values we have a function that takes two rentals, deconstructs one, combines the two `owned` parts, and executes a merge function on the borrowed parts.

This is not elegant but sensible, sadly `rental` does not give us an out-of-the-box facility to achieve this.

**Describe the solution you'd like**

Ideally, a case like this could be generally handled by a `rental` replacement.

**Notes**
Followup to #1015

**Comment by Licenser** [comment]
@Voultapher would it make sense / be possible to have a safe combine function in `self_cell`.

I'm thinking a trait for the `owed` part that indicates that it's combinable, could be pre-implemented for some types like linked lists where the values when concatenating won't move in memory and then have a merge function along the lines that `combine` takes.

**Comment by Licenser** [comment]
I don't think that would work, let me elaborate a bit on what happens in this case.

The `owners` a `Vec<u8>` that represents a memory region that contains the content of some `&str` (or rather `Cow<'_, str>` that are part somewhere inside the `dependant`. For context, this is the result of in-situ parsing (more often than not of JSON :sob:) were to avoid allocations strings remain in the source region of memory. This `owner` is never changed, or mutated.

To combine two of those self-referential structs we add a layer of indirection to the `onwer` so it becomes a `Vec<Vec<u8>>` 

We use a vector here to protect the inner `Vec<u8>` or more precisely the points inside of them from relocation. Adding to the outer vector might relocate the outer `Vec` but the pointers of the inner vector remain in place.

For consuming what we do is add the `owner` of the consumed struct (`Vec<Vec<u8>>`) to the `owner` data of the consuming struct. Then in the merge function, both `dependants` can be merged as their `owners` are combined in the consumed referential struct.

The suggestion of using LineValue as owned data won't really solve the problem as the result could not be emitted as a new event in its new form.

Performance would be a second issue, batches can span thousands or tens of thousands of events so the cost here would get out of hand quickly :(, we could probably defer doing the iteration step towards the very end which would negate the cost but change the latency characteristic (i.e. small cost on every event would become large cost on emitting) which isn't great for a streaming workload either.

**Comment by Voultapher** [comment]
Thanks for clarifying, so the result of this merge must be some Event again. During my refactoring I considered 2 solutions should this be the case:

A) Have Event be an Enum of a simple Event and MergedEvent
B) Add a new variant to to `Value` `RefArray(Vec<&'value Value<'value>>)`

But both options would probably affect all users of Value :/ plus it doesn't address the performance issue.

Regarding `Pin` that's a curious avenue, I was always under impression Pin means it has to be on the stack, but maybe it could also mean it can be heap allocated? I'll do some reading. Another avenue in general is you might not need a self referential struct library at all if you can guarantee that the struct is never moved, the Pin documentation even talks about this https://doc.rust-lang.org/std/pin/index.html#example-self-referential-struct maybe one could wrap this into a library ala pin_cell, the obvious benefit is you don't have to box the owner.

**Comment by Licenser** [comment]
While only slightly related, the Pin change works like a charm, not changing anything other than the guarantees the compiler offers but that's a nice gain :).

Neither of those options is really feasible since batches could be nested - since tremor is user-configurable and pipelines are graphs and include custom scripts. So aside from adding Enum or extending Value that would trickle down completely to the entire scripting language handling that new types, the sterilizer, deserializes, etc.

We didn't choose the current implementation lightly but so far it's the best set of tradeoffs we could find.

And yes perhaps it's worth investigating a custom pin/self-referential struct implementation, so far we shied away from that and preferred to rely on existing libraries (avoiding NIH and all that :joy: ) but it might be a lot of the same code that already exists and rental (or probably will exist in self_cell)

**Comment by Voultapher** [comment]
I'm wondering if we can find a way to use `Pin` in a Trait to express an interface capable of safely modelling this use case. We could only safely hand out references to the inner `Pin` objects and we still need some way of moving the dependent, although it ought to be safe to move the dependent as long as we guarantee the owner stays pointer stable.

**Comment by Licenser** [comment]
I could se a few possile options, but not sure about them since I'm not too firm on the current implementation in for self_ref but what I could see is having a function guarded by `when ..` or another trait that gets implemented when the type provided a certain type, for example:

(pseudocode, just a quick out of the top of my head draft)
```rust

trait Combinable<T> {
  fn consume(&mut self, other: Self, merge: ...) -> Result<...>;
}

impl<T> Combinable<UnsafeSelfCell<Pin<T>>>  {
...
} 
```

**Comment by Voultapher** [comment]
I've thought about it some more and I couldn't come up with a general approach that meets the stated goal of self_cell: 'this crate aims to be a good minimal solution to the problem of self-referential structs'. Still I think a solution using self_cell would be less hacky than with the current rental approach:

```rust
pub fn consume<'run, E, F>(&'run mut self, other: Self, join_f: F) -> Result<(), E>
where
    E: std::error::Error,
    F: for<'a> Fn(&mut ValueAndMeta<'a>, ValueAndMeta<'a>) -> Result<(), E>,
{
    let mut this_joined_cell = unsafe { self.unsafe_self_cell.borrow_mut() };
    let mut other_joined_cell = unsafe { self.unsafe_self_cell.borrow_mut() };

    // This owner modification is only save if NO references to the inner raw vec
    // have been stored in any event.
    this_joined_cell.owner.append(&mut other_joined_cell.owner);

    // Keeping other.parsed alive is ok as long as we ensure it's owner has been
    // moved in a pointer stable way.
    let other_parsed = std::mem::take(&mut other_joined_cell.dependent);
    join_f(&mut this_joined_cell.dependent, other_parsed);
}
```

This should get rid both of the transmutes and claiming the `ValueAndMeta` are alive for `'static` inside `join_f`.

**Comment by Licenser** [comment]
That looks decent, I think there are a few more rental-specific things to be tackled before moving to self_cell is easy but it looks like a promising path :).

Only diff I see is that the comment should probably talk about references about the `outer raw vec` instead of the `inner raw vec` but that's tiny.

**Comment by Voultapher** [comment]
Correct me if I'm wrong, the inner raw vec is the one that can get relocated. So it's addresses are not stable, but the slices to the inner u8 are pointer stable.

**Comment by Licenser** [comment]
Ah that distinction wasn't clear to me from the comment, yes that's correct.the vex itself can change location the data it holds won't

**Comment by Licenser** [comment]
Ah that distinction wasn't clear to me from the comment, yes that's correct.the vex itself can change location the data it holds won't
