### ISSUE TITLE
use `unwrap_used` clippy lint to check the use of unwrap

### ISSUE THREAD

**Issue by humancalico** [tremor-rs/tremor-runtime#1054]
Use [unwrap_used](https://rust-lang.github.io/rust-clippy/master/#unwrap_used), [expect_used](https://rust-lang.github.io/rust-clippy/master/#expect_used) or [unwrap_in_result](https://rust-lang.github.io/rust-clippy/master/#unwrap_in_result) clippy lints instead of grepping for unwrap here https://github.com/tremor-rs/tremor-runtime/blob/907a54fc800f12dda3fcf195ca9989b521310b6b/.github/checks/safety.sh#L39-L49

**Comment by Licenser** [comment]
We already use some of those lints, the extra bit of protection a non-rust script offers is however nice. It's easy to miss if one of those lints is missing from a lib.rs file (or was removed during development for convenience and forgotten to be put back - you see there is past pain here 😂  ) 

On the other hand, a change to the safety.sh stands out, it's an out-of-the-code-path edit that will quickly be noticed :). So 100% for using the lints, but I'd prefer to keep the convenient grep in there as well.

**Comment by Licenser** [comment]
Closing this as we'll be keeping both in place, no reason not to be overly cautious.
