### ISSUE TITLE
Enhance rest sink for optional GCP auth using service account tokens

### ISSUE THREAD

**Issue by darach** [tremor-rs/tremor-runtime#1081]
**Describe the problem you are trying to solve**

As a user of the Google Cloud Platform, I would like to be able to use service account based
authentication with the rest/http connectivity in tremor for ad hoc integration against GCP
APIs that are `http/json` based.

**Describe the solution you'd like**

Provide a mechanism to inject an authentication header deriving from authentication with
a specified authentication endpoint and injecting a header when the rest sink is configured
for external authentication.

If a configuration flag ( eg: `uses_gcp_auth` ) is set the `GOOGLE_APPLICATION_CREDENTIALS`
env variable should be resolved to a service account json which can be used to generate a token
for use via http basic authentication.

**Notes**

The mechanism already exists in the google storage sink in a form relatively easy to apply to
the generic rest endpoint as above.

**Comment by GaryPWhite** [comment]
I'm gonna give this a shot! Sounds fun and exciting :)

**Comment by mfelsche** [comment]
@GaryPWhite Awesome! Feel free to reach out if you need any help or bad jokes from us! :)
