### ISSUE TITLE
preprocess prints lexemes

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#1085]
**Problem**

`dbg preprocess` no longer prints the preprocessed source, as intended and documented, but instead is printing the lexemes at the moment.

**Steps**

1. `tremor dbg preprocess <file>`

**Possible Solution(s)**

The `preprocess` subcommand has caused a lot of confusion since its inception as it means different things to different people. At one point it printed the unprocessed source, at one point it printed the preprocessed source, now it prints the lexemes.

I would suggest removing it and instead add a `--preprocess` flag to both `src`, `lex`, and `ast`. Both those commands have not caused confusion in the past so they seem sensible. It also cuts down on subcommand making it easier for people to memorize. Lastly it has the advantage that we now have a repeated pattern, if `--preprocess` is passed the resulting output is generated after being passed through the preprocessor, if it isn't past it is not - this equally applies to all commands.

This could be even included in the `dot` command as part of #940

**Comment by mfelsche** [comment]
The current state of this is that the `tremor dbg preprocess` command is printing the lexemes after the lexer and preprocess steps. The `tremor dbg lex` is printing the lexemes after the lexer step and before the preprocess step.

It might need to require some changes in the way we parse queries and scripts if we want to be able to bypass the preprocessor. This only makes sense for debugging purposes as it will definitely fail for scripts/queries with `use` statements when generating the ast, as the preprocessor is our way to "execute" the `use` statements.

So it definitely makes sense for the `src` and `lex` subcommand, maybe not for the `ast`.

**Comment by Licenser** [comment]
Ja I don't know when that changed but that is neither the documented nor the intended behavior. Originally `tremor dbg preprocess` printed the source, somewhere over the past `<insert time here>` that behavior degraded to just printing the lexemes.

The documentation is pretty clear here:

```
    lex           prints lexemes
    preprocess    prints the preprocessed source
    src           prints source
```

originally:
* `lex` = raw lexcemes
* `src` = src with out preprocessor (and highlighting)
* `preprocess` = src with preprocessor (and highlighting)

**Comment by dak-x** [comment]
So what should be the intended behavior? Follow the docs?

**Comment by Licenser** [comment]
My preference would be going with the suggestion in the ticket using `--preprocess` as a flag for the commands that could either output preprocessed or non preprocessed versions. That solves the question of "what should preprocess output" since it no longer exists, and neither `src` nor `lex` are unclear in what they produce as an output
