### ISSUE TITLE
Add array::concatinate function

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#1113]
**Describe the problem you are trying to solve**

We are missing a function to concatenate two arrays

**Describe the solution you'd like**

```
array::concatinate([1], [2]) == [1, 2] 
```

**Comment by mfelsche** [comment]
lets call it `concatenate` and have an in-place optimization whenever we assign to one of the arguments:

```
let a = array::concatenate(a, b)
# or
let b = array::concatenate(a, b)
```

**Comment by Licenser** [comment]
I really like that but let's put the optimisation in a own issue as that would require a complete rewrite of the function implementation o.O

**Comment by aryan9600** [comment]
Do we want to return a brand new vector or append the items of the second vector into the first one? @Licenser @mfelsche

**Comment by mfelsche** [comment]
The way how functions work right now (arguments are passed in as immutable references, no access to anything external) we have to return a fresh array, unless we change how functions work.

**Comment by Licenser** [comment]
Ja, let's start with something simple, that way it's usable and optimize later. I am fairly sure eventually a lot of this will change and array concatenate might not be the most common case (or involve so small elements that it won't matter in many cases).  Let's not optimize until we know where we stand :)
