### ISSUE TITLE
clean up println and eprintln

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#1120]
**Describe the problem you are trying to solve**

We should investigate each `println` and `eprintln` to replace them, if sensible with `linfo`, `warn`, `debug` or `error`

**Comment by anonymousr007** [comment]
Hi @Licenser and @mfelsche, I want to trying to solve this issue and there in this issue we use [log](https://docs.rs/log/0.4.14/log/) crate. In this issue, first we investigate every single `println` and `eprintln` macros ?
