### ISSUE TITLE
`drop` in tremor-script should acknowledge `transactional` events

### ISSUE THREAD

**Issue by mfelsche** [tremor-rs/tremor-runtime#1162]
**Problem**

If an event is dropped with [`drop`](https://docs.tremor.rs/tremor-script/#drop) it is silently swallowed, although we should consider this event "delivered". The user intentionally dropped it and is done handling it, it should not be sent again and should not be considered "failed" in the sense that the application failed handling it.  It handled it and decided to drop it.

**Possible Solution(s)**

A [`drop`](https://docs.tremor.rs/tremor-script/#drop) should imply an `ack` CB event sent as contraflow insight, but only for `transactional` events.

**Problems**

The same "swallowing" happens every time an event is sent to a port that is not connected to anything. For example, if the `qos::backpressure` operator sends discarded events to the `overflow` port and it is not connected, those events will never be acknowledged or failed. It is also not 100% clear, whether events that end up in a dead end should be considered acknowledged or failed, since it might depend on context. @Licenser any thoughts on that?

**Comment by Licenser** [comment]
Oh darn, yes `overflow` does make it even more complicated as we'd, right now, don't know if something is connected or not in the operator.

**Comment by mfelsche** [comment]
This extends to sending to output ports of a pipeline too, that aren't connected to another pipeline or sink.

**Comment by Licenser** [comment]
yup, the joy!

**Comment by Licenser** [comment]
I think we went through this.
