### ISSUE TITLE
streams with the same name can be created

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#1212]
**Problem**

it is possible to create two streams with the same name, possibly leading to conflict and confusion for users

**Possible Solution(s)**

Provide an error when a stream gets redefined.

**Comment by mfelsche** [comment]
Minimal reproducer in tremor-query/trickle:

```
create stream snot;
create stream snot; // this should error

select event from in into snot;
select event from snot into out;
```
