### ISSUE TITLE
CSV Codec

### ISSUE THREAD

**Issue by mfelsche** [tremor-rs/tremor-runtime#1235]
**Describe the problem you are trying to solve**
CSV is a horrible but very common format and it is kindof efficient.
Lets support it.

**Describe the solution you'd like**

This codec should transform csv lines into arrays or into objects with the first line determining the field names.

**Questions**
Should this codec just return strings for each csv field or should it try and detect field types? Should it expect the same type across each line? Should the types be configurable?

**Comment by Agares** [comment]
Which flavours of CSV should be supported here? Are we talking RFC4180, or something else?

**Comment by Licenser** [comment]
I think 4180 would be a nice one, sticking to that standard also allows for later porting @geofflangdale's simdcsv over to rust :)

**Comment by mfelsche** [comment]
The [csv crate](https://crates.io/crates/csv) supports controlling the delimiter. I think a reasonable CSV support from us should be configurable there too. And i do think we can port the simdcsv C++ thingy to rust so it is as well configurable.

**Comment by darach** [comment]
By 4180 the IETF RFC is being quoted https://datatracker.ietf.org/doc/html/rfc4180
