### ISSUE TITLE
"docs" redirect is broken

### ISSUE THREAD

**Issue by jhermann** [tremor-rs/tremor-runtime#1239]
# Content Bug Report

## Page(s) Affected
The README.

## What needs to be fixed?
e.g. https://docs.tremor.rs/artefacts/onramps triggers a redirect that insert a spurious "/index" into the final URL, thus showing the "not found" page. Leads to https://www.tremor.rs/docs/index/artefacts/onramps, must be https://www.tremor.rs/docs/artefacts/onramps.

## Suggested Improvement
Use direct links, or fix "docs.tremor.rs" config.

**Comment by darach** [comment]
Hi @jhermann,

Well spotted, we switched from multiple sub-domains to a single unified web design a
week or two ago and we missed these links. Thanks for reporting the bug! 🚀

Darach.
