### ISSUE TITLE
module to convert sizes

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#1320]
**Describe the problem you are trying to solve**

In many configurations we have to specify sizes, they are (usually) defined as a number representing bytes, but it would be nice to have some more expressive ways.

**Describe the solution you'd like**

A module specifying functions to generate different sizes for example `size::mb(10) + size::mb(0.5)`  for 10mb and 5kb and enable this for the common sizes. This can fully be implemented in tremorscript

**Comment by mfelsche** [comment]
this is a good crate, but it doesn't yet have support for the `information` unit: https://github.com/paholg/dimensioned/issues/37

**Comment by Licenser** [comment]
that's a nice one OTOH it'd be really nice to have something in tremorscript native just for it being tremor native :D

**Comment by Agares** [comment]
Would it make sense for the module to expose functions like `size::kibi(2)` (will return 2048), `size::kilo(1)` (will return 1000), etc.? Correct me if I'm wrong but it's not possible to wrap numbers into user-defined types right now, so `size::MB` would still have to return unitless value, so the fact that it's bytes has to be kept in the comments/head of the reader anyway

**Comment by Agares** [comment]
Created a draft with my solution, happy to discuss further before I finish it up :)
https://github.com/tremor-rs/tremor-runtime/pull/1321
