### ISSUE TITLE
disable system metrics with special value for interval

### ISSUE THREAD

**Issue by jemshad** [tremor-rs/tremor-runtime#1352]
**Describe the problem you are trying to solve**

As of now, monitoring is enabled/disabled by including a key called `metrics_interval_s` in the corresponding section. It is difficult to include or remove a key completely in deployment configurations based on conditions. It would be much easier for the values to be altered, though.

**Describe the solution you'd like**

If the metrics can be enabled/disabled by specifying specific value for the key, it would be very easy to enable/disable them in different deployment configurations. ex: negative value may be used to disable metrics as negative values for interval doesn't make sense.

**Notes**

**Comment by Licenser** [comment]
`null` should disable system metrics
