### ISSUE TITLE
Find a typo

### ISSUE THREAD

**Issue by bobychaudhary** [tremor-rs/tremor-runtime#1378]
# Content Bug Report

## Page(s) Affected
Please list the page or pages this bug is present on. Please file one issue
for each bug you find. Only file an issue for a multi-page bug if the bug is
indeed the *same* bug, across the pages.

## What needs to be fixed?
Tell us what content is causing the issue and *how* it is causing the issue.
For example, "The code sample was confusing because it used advanced Rust features",
or "The call to action on the community page was vague".

## Suggested Improvement
(optional) Do you have a suggestion for how to fix the problem? Include your ideas
here.

# Minor typo mistake
```diff
-destabalize
+destabilize 
```

**Comment by bobychaudhary** [comment]
Can you please merge it!

**Comment by Licenser** [comment]
Heya, as mentioned in the ticket PR the DCO signoff is missing we can't merge PR's without it.
