### ISSUE TITLE
Issue with comment line parsing in trickle

### ISSUE THREAD

**Issue by jemshad** [tremor-rs/tremor-runtime#1405]
**Problem**

1. Comment lines are not parsed consistently in trickle file.
2. Console error reporting for the above problem adds an extra space which is confusing 

**Steps**

1. Create a comment line in trickle file beginning with two `#` signs
2. examples:
```
# this comment line works
#@ this also works as comment
#this works too
##this throws error!
```
3. Not only that lines beginning with `##` is not recognized as comment, the error reporting is also adding an extra space in the console output
```
tremor[461285]:    19 | #
tremor[461285]:    20 | # this works too
tremor[461285]:    21 | ## this throws error!
tremor[461285]:       | ^^^^^^^^^^^^^^^^^^^^^ Found the token `##  this throws error!` but expected one of
`#!config`, `create`, `define`, `mod`, `select`
```
4. As you can see, there was no space after `##` in the source code, but error report has a space

**Possible Solution(s)**

**Notes**

Output of `rustup --version`:  `rustup 1.24.3 (ce5817a94 2021-05-31)`
Output of `rustup show`:
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/jo481y/snap/rustup/common/rustup

no active toolchain
```
Output of `tremor --version`: `tremor 0.11.12 empty:000`

**Comment by Licenser** [comment]
Heya, this is more of a bad error message. A valid file requires content beyond comments, so the file itself isn't a valid tremor file - throwing en error is the correct behavior. Throwing this error however isn't ideal, it does say that it expects a create,define, mod or select (aka any kind of file content) but it'd be nicer to be more explicit around that.

A second thing to watch out for here is that `#` and `##` are not the same `##` is a  doc comment meaning it documents the definition following it, so a doc comment without a statement after it isn't valid syntax - again the error doesn't explain that so it's not ideal :).

**Comment by Licenser** [comment]
note 2nd bug

We strip leading spaces on comments to make them more readable and insert them back on printing however we always insert one instead of the 0-n that were present

**Comment by darach** [comment]
Fixed. We no longer expose the query language at the top level. And the underlying comment scanning issue has since been resolved.
