### ISSUE TITLE
Make default codec optional

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#1428]
**Describe the problem you are trying to solve**

While some of the connectors have a defacto default codec, others don't and using a "placeholder" default codec there can lead to unexpected behavior. 

**Describe the solution you'd like**

If we make the default codec callback optional having it return an Option we could selectively have some connectors default to a codec and others enforce selceiton by the user.

**Comment by mfelsche** [comment]
This has been released with 0.12
