### ISSUE TITLE
CI Improvements 2022

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#1452]
# This ticket is for the [CNCF spring mentorship 2022](https://mentorship.lfx.linuxfoundation.org/project/06ecd0e0-8d29-44e4-b249-80dd07704564)

**Describe the problem you are trying to solve**

We have a lot of headroom when it comes to improving the CI and the build process. Those improvements will make the day-to-day life of contributors better and gives end-users more frequent and up-to-date builds allowing them to be used in a more cloud-native fashion.

**Describe the solution you'd like**

This ticket contains two primary goals and a few stretch goals for those interested to dive deeper into certain areas.

Primary goals:

- [ ] Fully automate the release to the degree that there is a single command to run it.
- [ ] A script or `make` task for tagging, updating versions, docs, creating branches for major releases, creating artifacts, release notes etc.
- [ ] Integration with github actions

Stretch goals (any of those based on interest and focus):
- [ ] Investigate options for faster builds in the CI, there might be better ways of handling caching that are worth giving a try.
- [ ] Investigate the option to use musl (or other non-GNU libc's) for creating a statically linked tremor
- [ ] Additional package repositories to publish to (Ubuntu ppa, Fedora COPR, homebrew, snap, flatpak …)
- [ ] Improve automated benchmarking
  - [ ] Add benchmark results to PRs (same as code coverage does, and fail for significant decreases) 
  - [ ] Integrate hdr histogram display into benchmarks results
  - [ ] Improve benchmark UI to scale nicer on different displays
  - [ ] Add thresholds to benchmarks
  - [ ] Generalize the benchmarking tool to be useful for other projects
  - [ ] Integration with TremorBot (or discord bot)
  - [ ] Investigate the option of controlled parallelism for benchmarks

**Notes**

**Comment by aastha01chauhan** [comment]
@Licenser @mfelsche Hi! This project caught my eye while I was going through LFX mentorship projects list. I really liked the concept of it. Would love to engage with the community and contribute here this spring.

**Comment by mfelsche** [comment]
@aastha01chauhan @adithyaakrishna please apply via the LFX mentorship site. We will chose one of all applicants that applied with all required documents.

**Comment by aastha01chauhan** [comment]
Sure, thank you

**Comment by PrimalPimmy** [comment]
@mfelsche Hello! I got selected as a LFX mentee for this issue. I'll start working on this after I have a look around the issue, Hoping to receive proper guidance! I'll keep posting my progress and findings/issues here. As for the communication side, I only have tremor's discord server, let me know if there's anything else that I need to know.

**Comment by aastha01chauhan** [comment]
Hi, @PrimalPimmy Congratulations! I wish to start contributing here too. Can you send me Tremor's discord server so that I can connect with the community and receive guidance on how to get started? Or if you can help me to get started it would be great.

**Comment by Licenser** [comment]
this mentorship is concluded
