### ISSUE TITLE
Make compression levels and other parameters in processors configurable

### ISSUE THREAD

**Issue by darach** [tremor-rs/tremor-runtime#1726]
**Describe the problem you are trying to solve**

It would be useful to some production users to be able to configure and optimise compression levels. Currently
we have postprocessors such as `zstd` which hardcode a compression level ( `0` ) where more configurability
is desireable.

**Describe the solution you'd like**

Make compression algorithms more configurable perhaps via the `compress` postprocessor and add
appropriate parameters for setting optimization level by algorithm. Currently only `algorithm` is tunable.

**Notes**

**Comment by omkar-mohanty** [comment]
Hi, can I tackle this issue ?

**Comment by Licenser** [comment]
Hi @omkar-mohanty, sure go for it! Let me assign it to you :)
