### ISSUE TITLE
Reverse function for array

### ISSUE THREAD

**Issue by carolgeng** [tremor-rs/tremor-runtime#1790]
**Describe the problem you are trying to solve**

I would like to print out a string backwards. I have split the string into an array of characters, but there is no function to reverse the array.

**Describe the solution you'd like**

I would like a reverse function to be added for an array. Maybe a for loop could be used in this.

**Notes**

If this is an implementation of an [RFC](https://github.com/tremor-rs/tremor-rfcs) provide a URL
to the RFC this enhancement implements.

If this is a major enhancement or contribution an RFC may be required. It is ok to submit an enhancement
first and our core team will assist with major contributions. In general, major contributions should be
discussed with the community before submission.

**Comment by Licenser** [comment]
great catch, this is really missing!
