### ISSUE TITLE
`KnownKey` relies on a deterministic hash builder

### ISSUE THREAD

**Issue by marioortizmanero** [tremor-rs/tremor-runtime#1812]
**Problem**

When creating a `KnownKey`, the hash builder is discarded:

![image](https://user-images.githubusercontent.com/25647296/177310487-10a7ce8e-c133-42a9-abf4-bba5ea6f33af.png)

In order to ensure that the hash is going to be the same later on, the hash builder used for the pre-calculated hash (i.e., the screenshot) must be the *same one* from whatever hash map is being used. Some hashing algorithms start with a random seed, so if their hash builder isn't reused they return different hashes.

We currently use `halfbrown`'s hash builder, which is deterministic and is why everything works right now. But it seems somewhat wrong to rely on a deterministic hash builder with no warning whatsoever.

**Steps**

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=3aa7c4f91991ae7c0535202567df5013

**Possible Solution(s)**

* *Proper fix*: restructure `KnownKey` so that we are guaranteed that the hash builder is going to be the same. We currently  construct them with a `From<Cow>`. To fix this, we could either have a constructor that takes `Cow, HashBuilder`, or that initizalizes the `HashBuilder` itself and returns it in the constructor, too. That way it can be reused with the hash map. There may be another better solution which enforces this statically, since one could always forget to reuse it manually.
* *Realistic fix*: continue using the current `KnownKey` implementation if there are no plans to change the hashing algorithm. But there should be at least a warning in `KnownKey` so that noone changes it, explaining this issue. We could also enforce `halfbrown::DefaultHashBuilder` in the parameters of `KnownKey`'s methods, which should at least emit compile-time warnings.

**Comment by Licenser** [comment]
Looking over this in some context, this has to work on a default hash builder, not a shared one.

That's a hard requirement for the known key to work. The hash needs to be the same for any key in any map passed to it, no matter where it's created. having one hash builder for all that is virtually impossible.

So the `Proper fix` is not a option neither is it really proper :), in simd-json, we solve this by enforcing FxHash as a hasher when the known-key optimization is used. If there is a desire to replace the hasher it needs to follow the same rule: be deterministic for `Default`.

Perhaps one option is to create a tag-trait ` unsafe trait DeterministicWithDefault{}` and require the builder to fulfil that trait? That way when other hashersd are used at least the implementer understands that this is a requirement. It would follow the same logic as `Send` or `Sync` where a user can tag a struct with it if they guarantee it fulfiss the requirements even if the compiler can't know.

**Comment by Licenser** [comment]
This can't change
