### ISSUE TITLE
String formatting with args not working in definitions

### ISSUE THREAD

**Issue by mfelsche** [tremor-rs/tremor-runtime#1905]
**Problem**

Take this example config that tries to take the args values and format a string from them in the connector config:

```tremor
define flow snot
flow

  define connector client from http_client
  args
    host,
    port
  with
    config = {
      "url": "http://#{args.host}:#{args.port}/path"
    }
  end;
  
end;
```

Currently this results in an error like:

`| ^^^^^ The expression isn't constant and can't be evaluated at compile time`

**Steps**
1. Try to start tremor with the config above
2. See the error happen

**Possible Solution(s)**
Currently we only run the constant folder on the `with` values. The const folder cannot (or does not) replace the `args` paths with literals, so the constant folder reports that error.
Should we somehow resolve the `args` first to make this work?
What would be the most elegant way to solve this?

**Comment by mfelsche** [comment]
Interestingly, rewriting the above with the snippet below works just fine:

```tremor
define flow snot
flow

  define connector client from http_client
  args
    url
  with
    config = {
      "url": args.url
    }
  end;
  
end;
```

**Comment by Licenser** [comment]
It's not nice (aka not a solution), but does this work:

```
define flow snot
flow

  define connector client from http_client
  args
    host,
    port
  with
    config = {
      "url": "http://" + args.host + ":" +args.port +"/path"
    }
  end;
  
end;
```

Other then that I suspect we fail on string literal rewriting for const folding? We should definitely fix that

**Comment by mfelsche** [comment]
This works! Which hints at an issue inside the `ConstFolder`.

**Comment by Licenser** [comment]
Damn you `ConstFolder`, you had one job, folding consts and you didn't do it :sob:!

**Comment by Licenser** [comment]
This seems to be fixed
