### ISSUE TITLE
URI Decoder Functionality

### ISSUE THREAD

**Issue by nickjmh** [tremor-rs/tremor-runtime#194]
**Describe the problem you are trying to solve**
I need to decode URIs in my events.

**Describe the solution you'd like**
I would like a Tremor extractor that will decode the given URI in-place.

**Notes**
I've seen [Percent Encoding](https://en.wikipedia.org/wiki/Percent-encoding) in my raw URIs, as well as `\u0026`, so there are likely several encoding schemes that need to be considered.

**Comment by anupdhml** [comment]
Mostly tackled in: https://github.com/wayfair-tremor/tremor-runtime/compare/add-url-path-extractor

**Comment by Licenser** [comment]
there is also: https://github.com/tremor-rs/tremor-runtime/blob/main/tremor-script/src/std_lib/url.rs is anything missing to call this done?

**Comment by anupdhml** [comment]
Last time we talked about this, the open question was whether we should also make the WIP url extractor url-decode the extracted path. Now that a function to handle url decoding is already in the tremor-script stdlib, I think the extractor can only do base parsing and users can decode the path when needed.

We should also check whether query params are actually decoded in the current extractor implementation (looks like they are) and potentially align path decoding with it too, for consistency.

**Comment by Licenser** [comment]
`url::encode` and `url::decode` implement this now
