### ISSUE TITLE
Codec for handling DogStatsD datagram

### ISSUE THREAD

**Issue by Aramack** [tremor-rs/tremor-runtime#1950]
**Describe the problem you are trying to solve**
I'm attempting to process a DogStatsD datagram (https://docs.datadoghq.com/developers/dogstatsd) using the StatsD codec (https://www.tremor.rs/docs/0.12/reference/codecs/statsd/). Currently, if the datagram uses any of the extensions from the dogstatsd specification that aren't part of the official StatsD specification, the metric will be dropped. 

The two features that I'm looking to leverage tremor for are around applying conditional logic based upon the absence or presence of a tag. For example:
1. The ability to check for the presence absence of tag and apply filtering:
Drop this metric because it's missing the service tag: `missing.owner:1|c`
Keep this metric because it has the service tag: `has.owner:1|c|#service:ingress_gateway`

2. The ability to add new tags conditionally by looking up an existing tag in a predefined lookup table:
Input: `missing.owner:1|c|#service:ingress_gateway`
Output: `missing.owner:1|c|#service:ingress_gateway,technical_owner:site_reliability_engineering`

**Describe the solution you'd like**
While both of the above problems could likely be solved with string processing in a .troy script, I would like to see a new codec that can be used to process dogstatsd datagrams for the added performance benefits from a pure rust implementation.

**Notes**
Most of the functionality from the existing statsd codec can be reused. The extensions that dogstatsd adds are documented here:
https://docs.datadoghq.com/developers/dogstatsd/datagram_shell?tab=metrics

These include:
1. A extra data type, `d`, for distribution metrics in addition to the existing `c`, `g`, `ms`, `h` and `s`.
2. An optional comma separated list of strings. Using colons for key/value tags (env:prod). 
3. An optional container_id that can be used by the Datadog Agent to enrich DogStatsD metrics with additional container tags.

A complete datagram would look like:
`dogstatsd.distribution:123|d|@0.5|#env:dev|c:83c0a99c0a54c0c187f461c7980e9b57f3f6a8b0c918c8d93df19a9de6f3fe1d`

**Comment by mfelsche** [comment]
This is already on main and has been released with 0.13.0-rc.3
