### ISSUE TITLE
stdlib function for formatting nanosecond UTC timestamps as datetime strings

### ISSUE THREAD

**Issue by mfelsche** [tremor-rs/tremor-runtime#1978]
Add a function for generic formatting according to a format string:
```
std::datetime::format(<timestamp>, <format>, <timezone>)
```
with the third parameter optional and defaulting to `UTC`.

Some constants for common formats (rfc3339, http) would be nice for ease of use.

Additionally add some constants for commonly used timezones, like `UTC` or others. Optionally also a function to create a timezone from a diff from UTC in hours or minutes.

Invalid formats or timezones will lead to the function erroring.

The internal implementation can make use of the `chrono` crate. Supported format string escape sequences: https://docs.rs/chrono/latest/chrono/format/strftime/index.html#specifiers

**Comment by Licenser** [comment]
duplicate as this as part of #396
