### ISSUE TITLE
Tremor script utility(part of tremor tool) not working without DATA param

### ISSUE THREAD

**Issue by rajasimha1991** [tremor-rs/tremor-runtime#206]
**Problem**
The tremor scripting language tool is not working as described [here](https://docs.tremor.rs/operations/cli/#command-script) in docs. The DATA argument is not a required param as per the docs but if we run that command without DATA param it is not working.
If we provide the DATA param it is working as intended. 

**Steps**
1. I'm using the tremor docker container for testing.
2. `sudo docker run --rm --name tremor-test -v $(pwd)/scripts:/scripts -v $(pwd)/data:/data tremorproject/tremor:latest`
3. `sudo docker exec -it tremor-test bash`
4.  Run `./tremor-tool script run scripts/xyz.tremor` command without DATA param. You need to create a tremor file xyz.tremor before running this command. 

**Notes**

Output of `tremor-server --version`:
```
tremor version: 0.7.3
rd_kafka version: 0x000002ff, 1.2.2
tremor-runtime 0.7.3
```

**Comment by darach** [comment]
Raj, thank you for taking the time to report this bug!

Issue #200 will merge the `tremor-script` and `tremor-query` command line tools
back into `tremor-tool` so we'll link this issue from there and fix as part of that work.

**Comment by darach** [comment]
Closing as this is now a non-issue with #200 resolved.
