### ISSUE TITLE
DogStatsD codec merges messages from different payloads when no newline is present

### ISSUE THREAD

**Issue by Aramack** [tremor-rs/tremor-runtime#2120]
**Problem**
While testing out the DogStatsD codec (in 0.13.0-0.rc.8), we noticed that if there's no trailing new line on a payload, and the separate preprocessor is used multiple UDP packets can be merged together.

**Steps**
```
define flow dogstatsd
flow
  # The incoming DogStatsD metrics
  define connector udp_in from udp_server
  with
    codec = "dogstatsd",
    preprocessors = ["separate"],

    config = {
      "url":"127.0.0.1:8125",
    }
  end;

  use tremor::connectors;
  use tremor::pipelines;

  create connector console from connectors::console;
  create connector udp_in;
  create pipeline passthrough from pipelines::passthrough;

  connect /connector/udp_in to /pipeline/passthrough;
  connect /pipeline/passthrough to /connector/console;
end;
deploy flow dogstatsd;
```
Start the tremor server:
```

$ tremor server run ./main.troy 
tremor version: 0.13.0-rc.8
tremor instance: tremor
rd_kafka version: 0x000002ff, 1.8.2
allocator: snmalloc
Listening at: http://0.0.0.0:9898
```
Emit four test metric to the tremor server:
```
# echo -n: do not output the trailing newline
# echo -e: enable interpretation of backslash escapes
$ echo -ne "test.metric:0|ms|#env:dev\ntest.metric:0|ms|#env:dev" > /dev/udp/127.0.0.1/8125; echo -ne "test.metric:0|ms|#env:dev\ntest.metric:0|ms|#env:dev" > /dev/udp/127.0.0.1/8125
```
Output:
```
{"metric":{"metric":"test.metric","values":[0.0],"type":"ms","tags":["env:dev"]}}
{"metric":{"metric":"test.metric","values":[0.0],"type":"ms","tags":["env:devtest.metric:0"],"tags":["env:dev"]}}
```
The second and third metric get merged together. The fourth metric isn't processed because tremor is presumably still waiting for the newline to denote that the metric is complete.

**Possible Solution(s)**
Not sure where in code this would need to change, but the DogStatsD line format can support multiple messages per payload, but does not support UDP fragmentation. So seperate should be looking for a line end or the end of the packet, whichever comes first.

**Notes**

Output of `rustup --version`:
Output of `rustup show`:
Output of `tremor --version`:
```
$ tremor --version
tremor 0.13.0-rc.8
```

**Comment by mfelsche** [comment]
I think this one can be easily fixed by using the [`separate` codec](https://www.tremor.rs/docs/edge/reference/preprocessors/separate) a little different.

In its default configuration it is buffering up lingering content that didn't end with a newline and keeps it until it finds a newline, then emits it. 

It can be configured with `buffered: false`, so that it does not buffer and will thus exhibit the behaviour you want:

> So seperate should be looking for a line end or the end of the packet, whichever comes first.

Here is the above `main.troy adapted:

```
define flow dogstatsd
flow
  # The incoming DogStatsD metrics
  define connector udp_in from udp_server
  with
    codec = "dogstatsd",
    preprocessors = [
      {
        "name": "separate",
        "config": {
          "buffered": false,
          "max_length": 8192 // align this with the udp_server `buf_size`
        }
      }
    ],

    config = {
      "url":"127.0.0.1:8125",
      "buf_size": 8192
    }
  end;

  use tremor::connectors;
  use tremor::pipelines;

  create connector console from connectors::console;
  create connector udp_in;
  create pipeline passthrough from pipelines::passthrough;

  connect /connector/udp_in to /pipeline/passthrough;
  connect /pipeline/passthrough to /connector/console;
end;
deploy flow dogstatsd;
```
