### ISSUE TITLE
Make codecs configurable

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#2130]
**Describe the problem you are trying to solve**

A number of codecs have configuration options that aren't able to be exposed, some use pre-allocated buffers without user configuration others like json have two variants (`json` and `json-sorted`) allowing codecs to be configured would be nice.

**Describe the solution you'd like**

codecs could be configurable the same way preprocessor are with the name string or name + config struct

**Notes**
This is going to be a non breaking change / enhancement as we would keep the string variant, however at least the `json-sorted` codec would disappear

**Comment by mfelsche** [comment]
Codecs are already configurable in that way :)
