### ISSUE TITLE
Consider opening up path and record name syntax to wider syntax for better usability

### ISSUE THREAD

**Issue by darach** [tremor-rs/tremor-runtime#2337]
**Describe the problem you are trying to solve**

The use of backtick for idents, and double-quote for record field names can be confusing
at times.

```tremor
    1 | let $gcl_writer = {
    2 |   "timestamp": event."@timestamp"
      |                      ^ Found the token `"` but expected `<ident>`
    3 | };
 ```

**Describe the solution you'd like**

Given quoted strings are illegal as path segments:
* Allow double-quoted string as ident in path segment?

And as "@timestamp" is a legal field name in tremor perhaps:
* Allow record field names to be idents, or backtick idents

**Notes**

If we made the above changes, the following would be legal tremor, but illegal json:

```tremor
{ foo: "bar" }
```

However, if we made such a change to tremor it should always serialise to json correctly when a json
codec is in force.

As this changes usability and the language, would need an RFC and community discussion.

**Comment by Licenser** [comment]
I really don't like adding `"` as a way to quiet idents Having too many things to do the same thing makes a language confusing it also mixes the type of `string` and `ident` and that can become quite problematic say for example (those come to mind immediately but might have more problems with pattern matching for example):



## Ambiguity on the root node
```
let snot = 42;
let badger1 = `snot` ## <- now badger is 42
let badger2 = "snot" ## <- is this the string `"snot"` or is it the `42` since `"snot" is a valid path
```

if `badger2`  is the string `"snot"` then we have a problem as the `"snot"` in. `event."snot"` and `"snot"` have different meanings, if it is `42` then we have a problem since we can't assign strings any more if they resist as idents.

## ambiguity in array access

```
# The following transformations are valid:

# 1) you can replace any ident with a quite ident
event.snot == event.`snot`
# 2) you can replace any secondary path element with a array access syntax with a string key
event.snot == event["snot"]
# 1+2 => this means the following transformation is also valid: any quoted ident in a path is also valid as a string in the path element
event.`snot` == event["snot"]

# All of those transformations are reversible with

# Suggested add 3) any quoted ident in a path can be replaced with the string
event.`snot` == event."snot"

# if we follow the transformation chain
event.`snot` == event."snot"
# and
event.snot == event["snot"]
# it suggests that
event."snot" == event[snot]

# at which point we no longer can use variables as access keys.
```

**Comment by Licenser** [comment]
Added ambiguity:

if `event."snot"` is valid as an alternative syntax to `event["snot"]` does `event.3` become valid as a alternative syntax to `event[3]`?

**Comment by darach** [comment]
Yes, all good points. Its still worth looking into alternatives to find options to avoid folk tripping where there are syntax differences that aren't obvious. It may be good enough to have clearer hygienic errors, for example.

**Comment by darach** [comment]
We opted for a hygienic error rather than language changes as this is the simplest change and should be sufficient for folk that accidentally ```foo."bar"``` use quoted strings in path expressions to have a useful hint to the correct syntax.
