### ISSUE TITLE
Investigate compatibility w/ vector benchmarks

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#26]
[Vector](https://github.com/timberio/vector) has a number of benchmarks, we already have some to compare to Logstash but we might be able to adopt their [framework](https://github.com/timberio/vector-test-harness/) to get a larger number of them in a easier to reproduce fashion.

**Comment by darach** [comment]
Closing. Tremor has a reasonable set of benchmarks given its production users domains of endeavours. We can revisit if needed.
