### ISSUE TITLE
Build packages as part of the CI release process

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#376]
**Describe the problem you are trying to solve**

Packages are a good alternative to the docker image as they can make operations easier in some scenarios.

**Describe the solution you'd like**

We should build and publish packages as part of the release process

* [x] deb
* [x] rpm
* [ ] homebrew
* [x] tarball

**Comment by anupdhml** [comment]
starting point for the CI integration here: https://github.com/tremor-rs/tremor-runtime/tree/main/packaging

**Comment by Licenser** [comment]
Mac packages are already incloded in #280 , closing this issue
