### ISSUE TITLE
Print proper error for unterminated strings inside of string interpolation

### ISSUE THREAD

**Issue by anupdhml** [tremor-rs/tremor-runtime#402]
**Problem**

Right now, string literals in tremor-script don't allow `{` as a character.

This gets in the way of representing things like json string literals directly in tremor-script.

**Steps**

```
$ cat test.tremor 
let test = "{";

$ tremor-script test.tremor 
Error: 
    1 | let test = ";
      |              ^^ It looks like you forgot to terminate a string with a closing '"'
```

**Possible Solution(s)**

The left curly brace marks the start of the [string interpolation](https://docs.tremor.rs/tremor-script/#string-interpolation) and there does not seem to be a way to escape it in string literals when we don't want to interpolate -- we should allow for that.

**Notes**

For symmetry, we may also want to allow escaping for `}` (right now, `let test = "}";` is valid tremor-script), and throw an error when the right brace is used by itself in a string and unbalanced.

side note: I was not aware that the curly brace had so many names 😄  https://en.wikipedia.org/wiki/Bracket#Names_for_various_bracket_symbols

**Comment by Licenser** [comment]
That `{` needs to be escaped isn't a bug, it's part of allowing string interpolation.

The script:

```
let test = "{";
```

is not valid tremor script, the correct versionn is:
```
let test = "\{";
```

That said the error message is buggy, it should say:

```
Error: 
    1 | let test = "{";
      |              ^^ It looks like you forgot to terminate a string with a closing '"'
```

and ideally, mention that `{` for string interpolation if it's in the string, or the error could notice that it's a unterminated `}` and mention that?

**Comment by anupdhml** [comment]
Yes, let's improve the error message there -- ideally it can mention both that `{` is unterminated and that it is used for interpolation.

---

Right now, escaping `{` is not supported and this issue was for mainly fixing that.

>The left curly brace marks the start of the string interpolation and there does not seem to be a way to escape it in string literals when we don't want to interpolate -- we should allow for that.

I forgot to include the error for that earlier, with `\{`:

```
Error: 
    1 | let test = "\{
      |            ^^ An unexpected escape code '{' was found
```

Should be a small fix in the lexer: https://github.com/wayfair-tremor/tremor-runtime/blob/v0.8.0/tremor-script/src/lexer.rs#L1533

**Comment by Licenser** [comment]
let's make a second issue, I think both need to be fixed. I renamed this to reflect the initial post and will open a new one for the escape.
