### ISSUE TITLE
Use official elasticsearch rust client for elastic offramp

### ISSUE THREAD

**Issue by anupdhml** [tremor-rs/tremor-runtime#411]
There's an official elasticsearch rust client now: https://github.com/elastic/elasticsearch-rs

It's still in alpha but should be sufficient for our bulk indexing use in the elastic offramp. Looks to be more actively maintained than the [client](https://github.com/elastic-rs/elastic) we use currently, and will help with issues like https://github.com/wayfair-tremor/tremor-runtime/issues/408.

**Comment by SpyrosRoum** [comment]
Hello, I'm going to give this a try, it looks like that can be done by following rustc errors so it will probably be good for getting familiar with the code

**Comment by Licenser** [comment]
As a note, we're looking into extending functionality for delete and update on the sink/offramp so it'd be great to have those in a refresh as well :)

**Comment by SpyrosRoum** [comment]
That's good to know. I currently have some issues because I don't know how elasticsearch works and its concepts but once I get past that I'll what I can do about expanding the functionality!

**Comment by SpyrosRoum** [comment]
That's good to know. I currently have some issues because I don't know how elasticsearch works and its concepts but once I get past that I'll what I can do about expanding the functionality!

**Comment by mfelsche** [comment]
We use the official client now.
