### ISSUE TITLE
Unified wishlist for 0.9.x

### ISSUE THREAD

**Issue by darach** [tremor-rs/tremor-runtime#426]
Wish list of unified client work to be done:
* [x] generating cli doc (9.1?)
* [x]  improve tremor test integration ... so assert pass/fail status is obvious in ci ( no colors means not obvious without text prompt/hint )
* [x]  Patch CI to adopt new binary for api curl based tests
* [x]  Patch CI to adopt new binary for api tremor cli based tests
* [x]  Extend CI to support tremor stdlib unit style tests
* [x]  Extend CI to support tremor cli self hosted tests
* [ ]  Figure out code coverage against unified client

Wish list for cb/wal/ack/gd:

* [ ] A Qos operator for acks, and gated acknowledgement continuations in tremor-script+query
* [ ] An operator to expose circuit-breaker events to tremor-script+query
* [ ] An operator to expose WAL events to tremor-script+query
* [x] Document usage of in-memory WAL verses persistent
* [ ] Consider whether qos ack/cb/wal operators are distinct, a single operator or some mix thereof ...
* [ ] Example of ack/cb/wal qos in concert with state mechanism
* [ ] Raw vs best effort ( in mem + persistent ) vs lossless/guaranteed ( recoverable ) stream detection & reporting in runtime
* [ ] Look into different WAL flavours (ringbuffer etc)
* [ ] Look into more efficient WAL encoding

**Comment by mfelsche** [comment]
Closing this, as all open issues are tracked as new issues now.
