### ISSUE TITLE
fix packaging for 0.9

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#427]
with renaming the tremor CLI we broke packages, need to fix that.

**Comment by Licenser** [comment]
@anupdhml can this be closed?

**Comment by anupdhml** [comment]
Yes, I can close this now. The renaming issues are resolved and we packages can be built successfully.

But the musl binary is no longer statically linked and segfaults. We can track the fix there as part of https://github.com/tremor-rs/tremor-runtime/pull/430. And if we decide to push that fix for 0.9.1, we just need to disable musl packaging for 0.9.0.

I have added that item along with some packaging nice-to-haves to https://github.com/tremor-rs/tremor-runtime/pull/430.
