### ISSUE TITLE
String interpolation failure with module imports in tremor-script

### ISSUE THREAD

**Issue by anupdhml** [tremor-rs/tremor-runtime#445]
**Problem**

String interpolation fails with a runtime error when the script imports a module.

**Steps**

Run the following script from tremor-runtime main.

```
use std::random;
"{event} badger"
```

Output:
```
(main)$ echo '"snot"' | cargo run -p tremor-cli -- run interpolation_bug.tremor 
    Finished dev [unoptimized + debuginfo] target(s) in 0.22s
     Running `target/debug/tremor run interpolation_bug.tremor`
error processing event: Runtime error in function string::format/2: the format specifier at 2288 is invalid. If you want to use `{` as a literal in the string, you need to escape it with `{{`
Runtime error in function string::format/2: the format specifier at 2288 is invalid. If you want to use `{` as a literal in the string, you need to escape it with `{{`
```

When the module import is commented out, the script gives the expected output (`"snot badger"`). Also, without the trailing ` badger`, the interpolation succeeds.

**Notes**

For now, string-concatenation with `+` works fine for these needs.

The issue is there in 0.8 as well.

```
(0.8)$ cargo run -p tremor-script interpolation_bug.tremor
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/tremor-script interpolation_bug.tremor`
Error: 
    2 | "{event} badger"
      | ^^^^^^^^^^^^^^^^ Runtime error in function string::format/2: the format specifier at 2288 is invalid. If you want to use `{` as a literal in the string, you need to escape it with `{{
````

(side-note: the old tremor-script binary outputs runtime errors better with location information and that should be carried over to the new unified cli).

**Comment by Licenser** [comment]
It'll be fixed in 0.9, givent eh release time is around next week lets not bother with backporting it :)
