### ISSUE TITLE
Add ability to check if a variable is defined in tremor-script

### ISSUE THREAD

**Issue by anupdhml** [tremor-rs/tremor-runtime#446]
**Describe the problem you are trying to solve**

Tremor-script does not currently provide a way to check if a variable is defined or not (this is different from the case where a variable is set to `null` value, for which we can do [function-based](https://docs.tremor.rs/tremor-script/stdlib/std/type/#is_nullvalue) checks as well as pattern-match with [match](https://docs.tremor.rs/tremor-script/#match)).

This can be especially useful when working with meta variables as part of tremor-runtime, where -- as part of a pipeline node -- we may need to check if a certain meta variable is set or not (eg: from a previous pipeline node) and act accordingly. 

**Describe the solution you'd like**

A tremor-script function that will return true if a variable is defined and false otherwise.

**Comment by Licenser** [comment]
Is 'present' not allowing to check meta variables?

**Comment by anupdhml** [comment]
@Licenser had not thought to use `present` for this, thanks for the tip! Was used to only seeing it on the patterns.

just tested it out and it works as expected, even for meta variables.

```
match present $non_existent_var of
  case true => "present"
  default => "not present"
end;
```
I'll add this usage of `present/absent` to the docs and close this out.

**Comment by Licenser** [comment]
👍 the same could be written as:

```
match present $ of
  case %{present non_existent_var} => "present"
  default => "not present"
end;
```

I think, not sure which is the more ideomatic  one :)

**Comment by anupdhml** [comment]
Now documented as part of https://github.com/tremor-rs/tremor-www-docs/pull/29

**Comment by anupdhml** [comment]
And now available under: https://docs.tremor.rs/tremor-script/recipes/#check-if-a-variable-is-presentabsent

Closing this out.
