### ISSUE TITLE
Add a CII Best Practices badge to the README

### ISSUE THREAD

**Issue by caniszczyk** [tremor-rs/tremor-runtime#447]
This is a CNCF graduation requirement eventually, but good to do early 👍 
https://bestpractices.coreinfrastructure.org/en

**Comment by darach** [comment]
Were reviewing our CII now https://docs.tremor.rs/CII/ and tracking silver - AFAICR DCO was the only missing bit there...

**Comment by darach** [comment]
We now have the project tracked in the badges app here: https://bestpractices.coreinfrastructure.org/projects/4356

We are remediating the few remaining issues that means we don't quite have silver badge status and will add the badge to our top level README

**Comment by darach** [comment]
@caniszczyk Badge is now on the top-level README so closing this issue - we're remediating with an eye to silver status now. Would it be possible to widen the owner/maintainers of the badge project to the set of maintainers for tremor?
