### ISSUE TITLE
Add dynamic key to Kafka messages at Kafka offramp

### ISSUE THREAD

**Issue by anuprout** [tremor-rs/tremor-runtime#458]
**Describe the problem you are trying to solve**

Current implementation of Kafka offramp supports assigning a static key to each messages produced to Kafka via config file. However we have a requirement to add key to each messages dynamically.

**Describe the solution you'd like**

The dynamic key value can be assigned to the Tremor event metadata via Tremor script and the Kafka offramp can read this metadata and assign its value to the Kafka message key.

**Comment by anupdhml** [comment]
Closing this since the enhancement is now in main.
