### ISSUE TITLE
Detect Linkedness when IN/OUT ports are connected.

### ISSUE THREAD

**Issue by mfelsche** [tremor-rs/tremor-runtime#504]
**Describe the problem you are trying to solve**

Currently to have an onramp/offramp act as linked transport, the `linked: true` config value needs to be added.
This seems superfluous, as we can detect linkedness when something connects to the `IN` port of an onramp or to the `OUT` port of an offramp.

**Describe the solution you'd like**

Detect linkedness when when something connects to the `IN` port of an onramp or to the `OUT` port of an offramp.
Store the `linked` state in the onramp offramp struct and act on this like we do act now on the config value.

**Comment by Licenser** [comment]
lets add an option for also checking for 'error' when the user wants

**Comment by mfelsche** [comment]
It needs to be `err` :P
