### ISSUE TITLE
Additional Linked sources / sinks

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#509]
There are some additional sources that could take some linked transport goodness:

* [ ] stdin/stdout/stderr source
* [ ] tcp source
* [ ] tcp sink

## stdin/stdout/stderr source

read from stdin write to stdout, errors go to stderr

## tcp source

stream replie to requests over the tcp connection

## tcp sink 

stream replies for requests on a tcp connection

**Comment by aryan9600** [comment]
Do we just want to make the [`stdout`](https://docs.tremor.rs/artefacts/offramps/#stdout) and [`stderr`](https://docs.tremor.rs/artefacts/offramps/#stderr) offramps capable of linked transport, by adding support for `stdin`, or do we want to create a `stdin` onramp and then go ahead make it and the `stdout` and `stderr` offramps capable of linked transport?
