### ISSUE TITLE
Address some documentation gaps

### ISSUE THREAD

**Issue by anupdhml** [tremor-rs/tremor-runtime#513]
Collection of smallish doc improvements:

* [x] Document tremor-script tuple patterns (`%()`)
* [ ] Explicitly state that multiple expressions inside patterns are additive (i.e. OR logic is not supported there)
* [ ] Improve example for micro-format based predicate matching inside [array patterns](https://docs.tremor.rs/tremor-script/#matching-array-patterns) (current example returns an empty array result. document examples like this with output as well, for improved clarity).
* [ ] Usage example for config [preprocessor directive](https://docs.tremor.rs/tremor-query/pp/), with link to enabling pipeline metrics collection for monitoring
* [ ] Update monitoring [example](https://docs.tremor.rs/operations/monitoring/#example), including section on [enriching](https://docs.tremor.rs/operations/monitoring/#enriching) (old script code, pipeline yaml to trickle)
* [ ] Remove pipeline yaml in use in other docs like https://docs.tremor.rs/operations/configuration/
* [ ] Document ability to create custom pipeline inputs/outputs for trickle (`interfaces` in old pipeline yaml). examples like: `select event from in into out/route1`, which allows use of `route1` as the port for binding the pipeline to another artefact
* [ ] Document config file for new tremor cli (`~/.tremor/config.yaml`)
* [x] Document the interval unit (nanoseconds) for tremor-query [window definitions](https://docs.tremor.rs/tremor-query/#window-definitions), for when folks want to construct it outside of datetime functions (which requires use of `core` prefix right now)
* [ ] Document `,` as separator for multiple expressions in a case block

**Comment by darach** [comment]
These have been addressed or superceded. Closing.
