### ISSUE TITLE
Investigate kafka egress issue

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#532]
Get details on the issue

**Comment by anupdhml** [comment]
librdkafka issue detailing the observations here:
https://github.com/edenhill/librdkafka/issues/3118

**Comment by mfelsche** [comment]
Reopening as this issue was manifesting itself in different ways, of which we only fixed one.
What we didnt fix yet: Producer in kafka sink only produces 1 kafka MessageSet with 1 message every `queue.buffering.max.ms` if set to > 0.
