### ISSUE TITLE
Add append mode for file offramp writes

### ISSUE THREAD

**Issue by anupdhml** [tremor-rs/tremor-runtime#557]
**Describe the problem you are trying to solve**

Currently, writes from [file offramp](https://docs.tremor.rs/artefacts/offramps/#file) overwrite the specified file if it exists. We should also support appending to file instead of overwriting.

**Describe the solution you'd like**

Add a boolean param like `append` (or `overwrite`) to the offramp config, that controls the write behavior. Also see if it makes sense to switch the offramp default to be append instead of overwrite.

**Notes**

Support for file append in the stdlib file module: 
https://doc.rust-lang.org/std/fs/struct.OpenOptions.html#method.append

**Comment by mfelsche** [comment]
i would prefer a `write_mode` (or just `mode`) param that ca n be `append` or `overwrite` instead of a boolean value. It is more descriptive to my eyes.

**Comment by Licenser** [comment]
done
