### ISSUE TITLE
Catch assert failures from tremor tests for CI failures

### ISSUE THREAD

**Issue by anupdhml** [tremor-rs/tremor-runtime#563]
**Problem**

Assert failures on tremor tests do not currently bubble up as a CI failures. An example on a recent push:
https://github.com/tremor-rs/tremor-runtime/runs/1332794921#step:7:12

The test failure is not included in the end-summary as well (and there's more than one actual failure):
```
All Command Stats: Pass 358 Fail 0 Skip 0  Asserts 954 
Total Stats: Pass 358 Fail 0 Skip 0  Asserts 954 
Total Elapsed: 8s 873ms
```

**Steps**

To reproduce locally:

```
cargo run -p tremor-cli -- test api tremor-cli/tests
```

**Comment by Licenser** [comment]
fixed
