### ISSUE TITLE
Add git commit hashes to version for non-official release builds

### ISSUE THREAD

**Issue by darach** [tremor-rs/tremor-runtime#607]
**Describe the problem you are trying to solve**

Add git commit hashes to version for non-official release builds

**Describe the solution you'd like**

The feature branch name and commit hash should be represented in version information
emitted by tremor in the cli, api and other output for developer builds. This aids in replication
of issues and in identifying heritage of a build when multiple versions of tremor are in use
on the same environment.

**Notes**

If this is an implementation of an [RFC](https://github.com/tremor-rs/tremor-rfcs) provide a URL
to the RFC this enhancement implements.

If this is a major enhancement or contribution an RFC may be required. It is ok to submit an enhancement
first and our core team will assist with major contributions. In general, major contributions should be
discussed with the community before submission.

**Comment by GaryPWhite** [comment]
yea sounds like a good'n I'm gonna give this a swing

**Comment by GaryPWhite** [comment]
close? :)

**Comment by mfelsche** [comment]
C L O S E ! ! !
