### ISSUE TITLE
Add "stats_cb" callbacks to emit Kafka producer/consumer statistics added by "librdkafka"

### ISSUE THREAD

**Issue by anuprout** [tremor-rs/tremor-runtime#63]
Hi,

I am looking for an implementation of "librdkakfa" statistics where I can configure Tremor to emit the Kafka producer/consumer stats.  

I am looking for a stats_cb call back method where it can expose the stats via some API.

Here the link I am referring to for this implementation. 

https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md

Thanks

**Comment by Licenser** [comment]
This is a great idea!

**Comment by Licenser** [comment]
This is done, thx @mfelsche
