### ISSUE TITLE
Intercept OS signals and handle accordingly

### ISSUE THREAD

**Issue by darach** [tremor-rs/tremor-runtime#633]
**Describe the problem you are trying to solve**

Currently when suspending or interrupting tremor via OS signals, we do not perform
actions such as graceful shutdown or other administrative tasks.

**Describe the solution you'd like**

Runtimes such as the JVM have signal handling that allows developers and operators
to interact with the runtime. A good summary of signal types and how they are handled,
and whether or not signal handling can be disabled is documented by IBM's JVM for AIX
here:

https://www.ibm.com/support/knowledgecenter/en/SSYKE2_7.0.0/com.ibm.java.aix.70.doc/user/sighand.html

Minimally, when tremor is run as a server it should support graceful shutdown and perhaps a dump for
live debugging purposes. Ideally shutdown hooks should be provided for the graceful shutdown case.

**Comment by Licenser** [comment]
connectors incluided this
