### ISSUE TITLE
Support numeric literals with underscore

### ISSUE THREAD

**Issue by mfelsche** [tremor-rs/tremor-runtime#645]
**Describe the problem you are trying to solve**

In some places, tremor requires to enter nanoseconds. Those are usually huge numbers.
Typing and reading them is error-prone:

E.g.:

```
define tumbling window my_window
with
  interval = 1000000
end;
```

**Describe the solution you'd like**

We should allow underscores as parts of numeric literals, so they can be used for structuring them:

```
1_000_000
```

The lexer should ignore those characters when building up the numeric values, but should keep the actual representation around for reproducing the input for highlighting and errors.

**Comment by AswinTimalsina** [comment]
Hello! I am a beginner. Can you please suggest to me how to get started? I have no idea on which file shall I make changes. Thank you!

**Comment by Licenser** [comment]
Hi @AswinTimalsina it's great that you're interested in this :)!

A good starting point for this is the lexer, here  is where number handling is defined:

https://github.com/tremor-rs/tremor-runtime/blob/main/tremor-script/src/lexer.rs#L2336

I think that would get you a long way and at the bottom of the file are unit tests for lexing which will get you covered on that.

If you're curious there is an outstanding limitation with the lexer that it always returns an `i64`, if you want to adjust that to also allow u64 would be really cool :D but not needed.

Aside from that, feel free to hop by our [community discord](https://bit.ly/tremor-discord) we'll gladly help and answer questions :)
