### ISSUE TITLE
`deps.sh` gives false negatives for `env_logger` and `log4rs`

### ISSUE THREAD

**Issue by humancalico** [tremor-rs/tremor-runtime#789]
**Problem**

Upon checking for unused dependencies with [cargo-udeps](https://github.com/est31/cargo-udeps) it gives the following unused dependencies
1. env_logger
2. log4rs
3. openssl (this can be ignored as described [here](https://github.com/tremor-rs/tremor-runtime/pull/720/files#r565307364))

**Steps**

1. Install [cargo-udeps](https://github.com/est31/cargo-udeps)
2. run `cargo udeps --all-targets`

**Possible Solution(s)**

I am thinking of making a GitHub Action on top of `cargo-udeps` which can be used to replace the https://github.com/tremor-rs/tremor-runtime/blob/main/.github/checks/deps.sh script in our CI

**Notes**

Output of `rustup --version`:
```
rustup 1.22.1 (1980-01-01)
```
Output of `rustup show`:
```
active toolchain
----------------

stable-x86_64-unknown-linux-gnu (directory override for '/home/humancalico/code/tremor-runtime')
rustc 1.47.0 (18bf6b4f0 2020-10-07)
```
Output of `tremor --version`:
```
tremor 0.10.2 (DEBUG)
```

**Comment by Licenser** [comment]
Heya,
that's odd what command did you run to get those warnings? For me, the deps.sh script shows up no errors.

On udeps, it looks like it is nightly only and that's a bit of a concern. In our experience rust-nightly is hit and miss and can be in a 'non compiling' state for extended periods of time (running nightly/udeps today gives me 111 errors and 1427 warnings 😂 ).

That said once it works on stable getting rid of the hacky shellscript would be nice :D

**Comment by humancalico** [comment]
> that's odd what command did you run to get those warnings? For me, the deps.sh script shows up no errors.

Ohh I just realised that I wrote a confusing title. What I mean is that deps.sh should show those dependencies as unused but it doesn't
