### ISSUE TITLE
Binary not ( ! ) does not get lexed correctly

### ISSUE THREAD

**Issue by mfelsche** [tremor-rs/tremor-runtime#833]
**Problem**

The binary not `!` operator does not get lexed correctly.

**Steps**

1. Given this example script:

```tremor
let x = 12;
!x
```

2. When calling it with `TREMOR_PATH="$PWD/tremor-script/lib" cargo run -p tremor-cli -- run bin_not.tremor` 
3. The parsing step outputs:

```
Error: 
    1 | let x = 12;
    2 | !xx;
      | ^ Found the token `!x` but expected one of `!`, `\``, `$`, `(`, `+`, `-`, `<<`, `<doc-comment>`, `<end-of-stream>`, `<ident>`, `[`, `absent`, `args`, `bool`, `const`, `drop`, `emit`, `end`, `event`, `float`, `fn`, `for`, `group`, `heredoc`, `int`, `intrinsic`, `let`, `match`, `merge`, `mod`, `nil`, `not`, `patch`, `present`, `recur`, `state`, `window`, `{`
      |   NOTE: Did you mean to use `!`?
```

It seems to be the lexer who is at fault here as running `tremor dbg lex` on this script gives:

```
****************
* Lexemes - Lexical token stream before preprocessing
****************

   1:1 - 1:4     ∙     Let                               ∙          | let
   1:5 - 1:6     ∙     Ident                             ∙          | x
   1:7 - 1:7     ∙     Eq                                ∙          | =
   1:9 - 1:11    ∙     IntLiteral                        ∙          | 12
  1:11 - 1:11    ∙     Semi                              ∙          | ;
   2:1 - 2:2     ∙     Bad                               ∙          | !x
   2:2 - 2:4     ∙     Ident                             ∙          | xx
   2:4 - 2:4     ∙     Semi                              ∙          | ;
   2:5 - 2:5     ∙     EndOfStream                       ∙          | 
```

It seems the parser is messing with the lexing position and not recognizing the binary not operator correctly and then repeating the next character.

**Possible Solution(s)**

Fix it in the lexer.

**Notes**

This happens on current main (a6cd58fc85fabc8f1473e0fb7aa7ecb87f6da40b)

**Comment by anupdhml** [comment]
Existing issue for tracking the operator implementation here: https://github.com/tremor-rs/tremor-runtime/issues/46

We can close that one too when this is done.

**Comment by Licenser** [comment]
Matthias issue is definitely better, I'll close #46 :+1:

**Comment by mattwparas** [comment]
Anyone mind if I work on this?
