### ISSUE TITLE
[Kafka Onramp] Log assigned partitions on startup and rebalance

### ISSUE THREAD

**Issue by mfelsche** [tremor-rs/tremor-runtime#846]
**Describe the problem you are trying to solve**

We only log partitions numbers the source/onramp is subscribed to when the partition or topic is deleted in an error message. It would be helpful to have this information visible in the logs.

**Describe the solution you'd like**
Log on `info` level the partitions the source is assigned to or gets assigned to during rebalance. Also log partitions it is no longer assigned to.

**Comment by NamikoToriyama** [comment]
Hi! I want to try this as first issue.

One question. How is the log output?
I think there are standard output, text file, or external tool as external log output.

I haven't read the code in detail yet, so please let me know if there are any parts that are already logged.

**Comment by mfelsche** [comment]
For logging we use [log4rs](https://docs.rs/log4rs/0.13.0/log4rs/) and where the logs are put is configurable at tremor startup.

The code in question is all in this file: https://github.com/tremor-rs/tremor-runtime/blob/main/src/source/kafka.rs

We use this crate for interfacing with kafka as you will see: https://github.com/fede1024/rust-rdkafka/

You could use the post rebalance callback for the consumer to log the current state. But dig ahead, you might find a different, more suitable way. It is really interesting to dive into the kafka client machinery.
