### ISSUE TITLE
Log application shutdown

### ISSUE THREAD

**Issue by jemshad** [tremor-rs/tremor-runtime#847]
**Describe the problem you are trying to solve**

When the application is shutdown normally (using systemd in this case), some information about that in the logs would really help in troubleshooting to know what time the application stopped.

**Describe the solution you'd like**
Log lines saying application going for a shutdown

**Notes**
-NA-

If this is an implementation of an [RFC](https://github.com/tremor-rs/tremor-rfcs) provide a URL
to the RFC this enhancement implements.

If this is a major enhancement or contribution an RFC may be required. It is ok to submit an enhancement
first and our core team will assist with major contributions. In general, major contributions should be
discussed with the community before submission.

**Comment by Udbhavbisarya23** [comment]
Hi, if this issue is open, I'd like to take it up!

**Comment by mfelsche** [comment]
Go for it! :) Shall I assign you, so we make it official?

**Comment by Udbhavbisarya23** [comment]
Sounds good, Thanks!

**Comment by mfelsche** [comment]
Please be aware that all this is currently in a phase of being rewritten with #1077 So maybe you go look on that branch for making that change

**Comment by Udbhavbisarya23** [comment]
I've got the repository set up on my system, but I would like to replicate this behaviour locally. Could I please get more insight into this?

**Comment by mfelsche** [comment]
We have a `systemd` service file: https://github.com/tremor-rs/tremor-runtime/blob/main/packaging/distribution/etc/systemd/system/tremor.service

You can use this to spawn tremor on your system and then stop it. Upon stop it should log something.

**Comment by Udbhavbisarya23** [comment]
I'll have a look into this. Thank you for the quick response!

**Comment by Licenser** [comment]
we log sutdowns with the connector changes
