### ISSUE TITLE
More run away memory for windows and group by

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#849]
**Problem**

Size-based grouped windows do not evict empty groups even when `emit_empty_windows` is set. In a streaming context, where groups are likely to change, such as using size-based windows for correlation, this will lead to unbounded memory growth.

context: https://github.com/tremor-rs/tremor-www-docs/pull/89/files#r595935865

**Possible Solution(s)**

Evict empty groups if `emit_empty_windows`  is false

**Comment by mfelsche** [comment]
This is not only limited to size based groups. We keep the groups around forever unless `eviction_period` is set, in which case we clear out the group data for which we didnt receive events.

We reset the aggregation states every time we emit from a window, so these are not unbounded. It is just the group_data bookkeeping map is never cleared out (unless `eviction_period` is used).

**Comment by mfelsche** [comment]
This is fixed on main with #1143
