### ISSUE TITLE
Allow outputting `dbg ast`, `dbg src`, `dbg preprocess` info without line numbers

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#854]
**Describe the problem you are trying to solve**

When outputting data from `dbg` subcommand the line numbers are always prefixed, this make the json output nonreusable, but it would be nice to be able to put it through other tools

**Describe the solution you'd like**

A flag to print the json without line numbers or other modifications, for example `--raw/-r` would work well to remove all additional prints.

**Comment by srisatya1197** [comment]
Is anyone working on this issue , If not I want to work on this.

**Comment by Licenser** [comment]
Hi @srisatya1197 I don't think anyone claimed this issue yet :) and that would be awesome to have that added!!

This is also a wonderful first issue it's fairly simple and will help to get a little intro into tremor :) let me assign it to you and if you want come by our discord over the next few days and we'll help you get started?

**Comment by srisatya1197** [comment]
Thank you so much @Licenser Sir. I want to start and need help if I get stuck anywhere .

**Comment by Licenser** [comment]
Ah yes, we use a automated Code of Conduct system that requires community members to accept the CoC before being able to actively participate.

if you look in the `#rules` channel there is a message detailing it with a little :heavy_check_mark: on the bottom you can click to accept it.

**Comment by srisatya1197** [comment]
ok thank you so much Sir.

**Comment by dak-x** [comment]
* Do you wish to also remove the line spans which are output by `preprocess`. 
* Should `banner` be also removed if `raw` flag is set.
* Do you wish to also add an option to remove  the `node-output` from the ast. This param only stores the line spans for each token from the little glance I made at the AST types.
 Also I do not see a json output for `dbg src/pp` ( though I have only tested for `*.trickle` files ).

**Comment by Licenser** [comment]
You stumbled over a regression here `preprocess` isn't supposed to print out a token stream like `lex` but rather the preprocessed source somewhere along the line that got lost. Raw should also remove the banner as it's intended for machine processing.

- `dbg ast` should print the AST in json. `--raw` here should output plain JSON so that it could be piped to, say JQ.
- `dbg src` should output the source code. `--raw` should output it without line numbers or highlighting so it can be run by `tremor run`
- `dbg preprocess` should output the the preprocessed source. `--raw` should print it without line numbers or highlighting so it can be run by `tremor run`

`dbg  preprocess` is currently broken however :(

**Comment by Licenser** [comment]
I don't think the PR solved the issle did it?

**Comment by mfelsche** [comment]
I think it does. It added a `--raw` flag to the `dbg` subcommand which disables linenumbers, highlighting and banner. What else is there to do?

**Comment by Licenser** [comment]
:facepalm: ja it does I was in the wrong issue I'm  multitasking too much, sorry!
