### ISSUE TITLE
dbg ast generate invalid json (simd-json bug)

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#855]
**Problem**

dbg ast generates invalid JSON, this is a bug in simd-json.

**Steps**
Run the test file:
```tremor
a.b
```

through `dbg ast`

the output is:
```json
[
  {"Imut": {"Path": {"Local": {
    "idx": 0,"is_const": false,"mid": 4,"segments": [
      {
        "Id": {"mid": 3
        }
      ]
    }}}}
  ]
```
**Possible Solution(s)**

**Notes**

Output of `tremor --version`: 0.10.2

**Comment by mfelsche** [comment]
Or could it be a bug in simd_json handling the `skip` property or any other part used in the serialize process? This is how we setup `Serialize` for the `Segment::Id`:

```
Id {
        /// Key
        #[serde(skip)]
        key: KnownKey<'script>,
        /// Id
        mid: usize,
    },
```

**Comment by Licenser** [comment]
nah skip is handled by serde, simd-json never sees that, already found and fixed it :D the serializer was too optimized, it optimized a `}` away for the struct variant of an enum

**Comment by Licenser** [comment]
The good news is that won't affect anything in tremor but AST printing, we don't rely on the serde::Serializer for anything on the critical path as it's just too slow and simd-json's value serializer wasn't affected as it's completely different :D

**Comment by Licenser** [comment]
This is resolved with a fix in simd-json :+1:
