### ISSUE TITLE
Request to add source IP as event metadata for UDP onramp

### ISSUE THREAD

**Issue by anuprout** [tremor-rs/tremor-runtime#890]
**Describe the problem you are trying to solve**

Request to add the source IP as event metadata for UDP packets.

**Describe the solution you'd like**

The peer info can be added here. https://github.com/tremor-rs/tremor-runtime/blob/5ba1c3382b406cf7387ba28fbe65b9525d51a7f9/src/source/udp.rs#L93

**Comment by Licenser** [comment]
The source IP is part of the event URI that identifies the origin of the event. `origin::host()`  will give you the origin host (IP)

**Comment by Licenser** [comment]
I opened #891 to remind us to unify this and clean up the differences in origin handling

**Comment by anuprout** [comment]
@Licenser yes, if the origin URI is unified, then we can use that as a standard way of getting the source info. Thnks
