### ISSUE TITLE
Configurable codecs

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#927]
**Describe the problem you are trying to solve**

Some of the codecs would benefit a lot from being configurable so some settings can be passed in.

Two examples:

 * Timezone for the syslog codec
 * pretty printing for the JSON codec

**Describe the solution you'd like**

**Notes**

this should be part of the troy RFC as it changes those things

**Comment by mfelsche** [comment]
The means for this is added in the work on `connectors`, making the codecs actually configurable still needs to be done.

**Comment by Licenser** [comment]
This is done!
