### ISSUE TITLE
WAL connector

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-runtime#936]
**Describe the problem you are trying to solve**

Currently we offer a `WAL` operator, this is problematic in a few ways. Our bias for pipelines has always been to avoid blocking operations, a `WAL` is by definition very blocking. It also makes the migration of pipelines problematic since now a persistent state exists. It also is an operator that can generate GD events which means it enforces special handling, removing it might allow us to simplify and sanitize some of the handlings of GD events in the pipeline.

**Describe the solution you'd like**

WAL as any other blocking operation should be a linked offramp, it naturally lends itself to this by the WAL by acking of failing as any other connector.

The WAL operator would be depricated and removed a release later

**Notes**

It could be worth investigating alternatives to `sled` for the WAL as part of this.

**Comment by mfelsche** [comment]
Until there is no clarification on this issue: https://github.com/spacejam/sled/issues/1333 we should consider sled as not-suitable for a persistent WAL. Also our access pattern for the WAL is never multi-threaded.

RocksDB seems to have a nice compaction feature, that might suite our WAL use case, called [FIFO Compaction](https://github.com/facebook/rocksdb/wiki/FIFO-compaction-style).

**Comment by Licenser** [comment]
RocksDB, pulling in a huge C-dependency has a number of drawbacks:

1) longer compile times
2) more compilation dependencies
3) a more likely to be flaky c to rust interface
4) CPU dependant compilation outside of rust

In addition is RocksDB notoriously hard to configure and tune correctly.

**Comment by mfelsche** [comment]
After discussing this, the best solution we could come up with is a filesystem based ring-buffer, implemented as two different files and the pointers in the ring-buffers as separate files. This way the size of the files is capped and needs to be configured. We can elaborate our ideas should anyone pick this issue, which we would be super happy about.

**Comment by Licenser** [comment]
This is implemented
