### ISSUE TITLE
log line to indicate initialization completion.

### ISSUE THREAD

**Issue by jemshad** [tremor-rs/tremor-runtime#986]
**Describe the problem you are trying to solve**

Trying to find from the logs when tremor has completed reading all the config files and done with the initialization phase.

**Describe the solution you'd like**

A line in the log that says something like, `Initialization over, application ready for events` or something on those lines, but you get the idea.

**Notes**

Because of the interleaved log lines, two nodes with the same configuration is not having log lines in the same order. So there isn't a single pattern which would tell us that tremor is now ready.

If this is an implementation of an [RFC](https://github.com/tremor-rs/tremor-rfcs) provide a URL
to the RFC this enhancement implements.

If this is a major enhancement or contribution an RFC may be required. It is ok to submit an enhancement
first and our core team will assist with major contributions. In general, major contributions should be
discussed with the community before submission.

**Comment by Licenser** [comment]
Puh, since sources and sinks can be reloaded / started and stopped this would probably have to be on a per source level. Would something like:

"Circuit breaker open" (with a more helpful phrasing)

for an onramp solve your need? It doesn't mean that it's ready as that's a bit application-specific (i.e. if it's Kafka ready depends on the connection and server too) but it would be an indication that the engine is ready to process them.

**Comment by jemshad** [comment]
Yeah some indication of completion of the phase of reading all the configuration files, connecting the pipelines and other pieces together etc. I am not sure if this description really fits the overall use case.

**Comment by Licenser** [comment]
Since we've the API and config loading goes over the same internal interact that's all asynchronous but the 'CB open' is when the system has decided this onramp is ready to receive data and the connections are working.

**Comment by mfelsche** [comment]
This is done by the work on `connectors`.

**Comment by Licenser** [comment]
connectors has been merged
